-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://www.shore.co.il/git/shell-pre-commit/
    sha: v0.5.4
    hooks:
    -   id: shell-lint
        files: bundle_certs
    -   id: shellcheck
        files: bundle_certs
