repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.3
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: trailing-whitespace
-   repo: https://github.com/adarnimrod/shell-pre-commit
    sha: v0.6.0
    hooks:
    -   id: shell-lint
    -   id: shellcheck
