---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: trailing-whitespace

  - repo: https://github.com/adarnimrod/shell-pre-commit
    rev: v0.6.0
    hooks:
      - id: shell-lint
      - id: shellcheck

  - repo: https://github.com/myint/rstcheck
    rev: master
    hooks:
      - id: rstcheck

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.25.0
    hooks:
      - id: yamllint
