-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 97b88d9610bcc03982ddac33caba98bb2b751f5f
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://www.shore.co.il/git/shell-pre-commit/
    sha: v0.1.0
    hooks:
    -   id: shell-lint
        files: bundle_certs
-   repo: local
    hooks:
    -   id: test
        name: make test
        language: system
        entry: make test
        files: bundle_certs|Makefile
