---
language: python
python: "3.5"
dist: trusty
sudo: false
group: beta
cache:
  - pip
  - directories:
      - $HOME/.pre-commit

addons:
  apt:
    sources:
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu trusty-backports main universe multiverse'
    packages:
      - mawk
      - openssl
      - curl
      - build-essential
      - shellcheck

install:
  - pip install pre_commit

script:
  - pre-commit run --all-files

notifications:
  email: false
