---
language: python
python: "3.6"
dist: trusty
sudo: false
group: beta
cache:
  - pip
  - directories:
      - $HOME/.cache

addons:
  apt:
    packages:
      - mawk
      - openssl

install:
  - pip install pre_commit | cat

script:
  - pre-commit run --all-files
  - bats test.bats || true

notifications:
  on_failure: never
  email: false
