---
language: python
python: "3.5"
dist: trusty
sudo: false
group: beta
cache:
  - pip
  - directories:
      - $HOME/.pre-commit
      - $HOME/.cabal
      - $HOME/.ghc

addons:
  apt:
    packages:
      - mawk
      - openssl
      - curl
      - cabal-install
      - ghc

env:
    PATH: $PATH:$HOME/.cabal/bin

install:
  - cabal update && cabal install shellcheck
  - pip install pre_commit | cat

script:
    - pre-commit run --all-files
    - bats --tap tests/

notifications:
  on_failure: never
  email: false
